version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  unit-test:
     machine:
      image: android:202102-01
    resource_class: large
    shell: /bin/bash
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/save-gradle-cache
      - android/save-build-cache

      - run:
          name: install new Gradle
          command: |         
              which bash
              ls -l /usr/bin/bash
              ls -l /bin/bash
              wget https://services.gradle.org/distributions/gradle-6.5-all.zip --no-check-certificate
              sudo unzip gradle-6.5-all.zip -d /usr/local/
              NEW_PATH=$(echo $PATH | sed -e 's/gradle-6.8.3/gradle-6.5/g')
              echo "export PATH=\"$NEW_PATH\"" >> $BASH_ENV
              source $BASH_ENV
              gradle -v
              echo $PATH
              which bash
              ls -l /usr/bin/bash
              ls -l /bin/bash
      - run:
          name: check gradle version
          command: |
              gradle -v
      - run:
          shell: /bin/bash
          command: ls -la /bin/bash
          when: always

workflows:
  test-and-build:
    jobs:
      - unit-test


