version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  unit-test:
    machine:
      image: android:202102-01
    steps:
      - checkout
      - run:
          name: install new Gradle
          command: |         
              wget https://services.gradle.org/distributions/gradle-6.5-all.zip --no-check-certificate
              sudo unzip gradle-6.5-all.zip -d /usr/local/
              echo 'export PATH=/usr/local/gradle-6.5/bin:$PATH' >> $BASH_ENV
      - run:
          name: check gradle version
          command: |
              gradle -v

workflows:
  test-and-build:
    jobs:
      - unit-test


